apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-client-config
  namespace: munggae
data:
  my.cnf: |
    [client]
    default-character-set = utf8mb4
    [mysql]
    default-character-set = utf8mb4
    [mysqld]
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
    init_connect='SET NAMES utf8mb4'
    max_connect_errors = 5

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: munggae
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-spring-deployment
  namespace: munggae
  labels:
    app: mysql-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-spring
  template:
    metadata:
      labels:
        app: mysql-spring
    spec:
      containers:
        - name: mysql-spring-db
          image: eddykim3396/ktb-10-db:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-client-config
              mountPath: /etc/mysql/my.cnf
              subPath: my.cnf
              readOnly: true
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-client-config
          configMap:
            name: mysql-client-config
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-munggae-service
  namespace: munggae
spec:
  selector:
    app: mysql-spring
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
