apiVersion: v1
kind: Service
metadata:
  name: munggae-spring-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"    # ALB 유형 설정
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing" # 외부 접근 허용
spec:
  type: ClusterIP
  selector:
    app: munggae-spring-service
  ports:
    - protocol: TCP
      port: 80              # ALB의 포트
      targetPort: 8081      # 컨테이너의 포트
