apiVersion: apps/v1
kind: Deployment
metadata:
  name: munggae-spring-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: munggae-spring-service
  template:
    metadata:
      labels:
        app: munggae-spring-service
    spec:
      containers:
        - name: munggae-spring-service
          image: ella00/munggae-be-spring:120
          ports:
            - containerPort: 8081
          resources:
            requests: # 최소 리소스 요청
              cpu: '200m'
              memory: '256Mi'
            limits: # 최대 리소스 제한
              cpu: '500m'
              memory: '512Mi'
          volumeMounts:
            - name: config-volume
              mountPath: /config/application.yml
              subPath: application.yml
          env:
            - name: SPRING_CONFIG_LOCATION
              value: 'optional:file:/config/application.yml'
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: munggae-spring-secrets
                  key: aws-access-key
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: munggae-spring-secrets
                  key: aws-secret-key
            - name: S3_URI
              valueFrom:
                secretKeyRef:
                  name: munggae-spring-secrets
                  key: s3-uri
            - name: CLOUDFRONT_URI
              valueFrom:
                secretKeyRef:
                  name: munggae-spring-secrets
                  key: cloudfront-uri
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: munggae-spring-secrets
                  key: jwt-secret-key
            - name: CLIENT_SECRET_URI
              valueFrom:
                secretKeyRef:
                  name: munggae-spring-secrets
                  key: client-uri
            - name: KAKAO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: munggae-spring-secrets
                  key: kakao-client-id
            - name: KAKAO_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: munggae-spring-secrets
                  key: kakao-redirect-uri
            - name: TZ
              value: Asia/Seoul
      volumes:
        - name: config-volume
          configMap:
            name: munggae-spring-config
            items:
              - key: application.yml
                path: application.yml
