apiVersion: apps/v1
kind: Deployment
metadata:
  name: munggae-ai-deployment
  labels:
    app: munggae-ai

spec:
  replicas: 1
  selector:
    matchLabels:
      app: munggae-ai
  template:
    metadata:
      labels:
        app: munggae-ai
    spec:
      containers:
        - name: munggae-ai
          # image: ella00/munggae-ai:9
          image: ella00/munggae-at:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: munggae-ai-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: 'external' # ALB 유형 설정
    service.beta.kubernetes.io/aws-load-balancer-scheme: 'internet-facing' # 외부 접근 허용
spec:
  type: ClusterIP
  selector:
    app: munggae-ai
  ports:
    - protocol: TCP
      port: 8000 # ALB의 포트
      targetPort: 8000 # 컨테이너의 포트
