apiVersion: apps/v1
kind: Deployment
metadata:
  name: munggae-ai-deployment
  labels:
    app: munggae-ai

spec:
  replicas: 2
  selector:
    matchLabels:
      app: munggae-ai
  template:
    metadata:
      labels:
        app: munggae-ai
    spec:
      containers:
        - name: munggae-ai
          image: ella00/munggae-ai:29
          #image: eddykim3396/ktb-10-ai:latest
          ports:
            - containerPort: 8000
          resources:
            requests: # 최소 리소스 요청
              cpu: '200m'
              memory: '256Mi'
            limits: # 최대 리소스 제한
              cpu: '500m'
              memory: '512Mi'
---
apiVersion: v1
kind: Service
metadata:
  name: munggae-ai-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: 'external' # ALB 유형 설정
    service.beta.kubernetes.io/aws-load-balancer-scheme: 'internet-facing' # 외부 접근 허용
spec:
  type: ClusterIP
  selector:
    app: munggae-ai
  ports:
    - protocol: TCP
      port: 8000 # ALB의 포트
      targetPort: 8000 # 컨테이너의 포트
