apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: munggae-ingress-v1
  annotations:
    kubernetes.io/ingress.class: 'alb'
    alb.ingress.kubernetes.io/healthcheck-path: /healthcheck
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '10'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/healthcheck-healthy-threshold-count: '3'
    alb.ingress.kubernetes.io/healthcheck-unhealthy-threshold-count: '3'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}, {"HTTP": 8000}]'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=60
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:590184100354:certificate/5ed4bd7f-3df3-49c5-84bf-1707904eb58e
spec:
  rules:
    - host: api.munggae.site # Ingress에서 처리할 호스트
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: munggae-spring-service
                port:
                  number: 80
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: munggae-ai-service
                port:
                  number: 8000
